### PR TITLE
Fix judgment of promise

### PR DESCRIPTION
**Pull request by banbanchs**
`isValid.constructor` is `Promise`

pic

### CODE REVIEW

**Comment by huei90** [comment]
Hi @banbanchs Thanks for the fixing. :beers: 

Would you mind give me more information about this fix?

**Comment by banbanchs** [comment]
If `isValid` is a Promise object, then its constructor is Promise not Object.

My fix is to check if `isValid` is object and `isValid.then` is a function.(if it has `then` function, then we can assume it is a Promise obj.

sorry my poor English :)

**Comment by huei90** [comment]
I'm not sure about this yet. Would you mind show me your code that can output the Promise constructor?

**Comment by hungdoan2** [comment]
Hi @banbanchs , actualy @huei90 have already checked for the case of "isValid is a object but not a promise object ".
Look at `checkValidation`  function. You will get that : if the validation expression is an object, It always throw an invalid validation.
=> So, His  code is fine.
But I agree that your fix will help the code be more cleaner and easier to read.

p/s: any way. We can use $q.when(value,..) => this function will handle the checking for us. But The validate function is not always a promises; Hence, I'll use the native way for better performance.

**Comment by banbanchs** [comment]
@huei90 @hungdoan2 Oh, it is angular version problem! This bug only show after angular 1.4.4 since constructor is set to `Promise` not `Object`

https://github.com/angular/angular.js/blob/master/CHANGELOG.md

https://github.com/angular/angular.js/pull/10697/files#diff-8c0e145b42564a7c2838e221e0a0322aR274

**Comment by huei90** [comment]
Ok thanks @banbanchs I left it here, because that's the angular1.4 stuff.

**Pull request closed without merging**
