### PR TITLE
Fixed Issues #111

### PR DESCRIPTION
**Pull request by think2011**
I modify [L371](https://github.com/huei90/angular-validation/blob/master/dist/angular-validation.js#L371) and [L574](https://github.com/huei90/angular-validation/blob/master/dist/angular-validation.js#L574)

``` javascript
// L371
var focusElements = {};

// L574 begin
var setFocus = function(isValid) {
    if(isValid) {
        delete focusElements[index];
    } else {
        focusElements[index] = element[0];

        $timeout(function() {
            focusElements[Math.min.apply(null, Object.keys(focusElements))].focus();
        }, 0);
    }
};

isValid.constructor === Object ? isValid.then(setFocus) : setFocus(isValid);
```

It's working for me.

If this PR is useful, please review code and code comment, because my English is very poor :)

### CODE REVIEW

**Comment by huei90** [comment]
Thanks @think2011 Do you mind give some explanation about this fix?

**Comment by huei90** [comment]
Please try `grunt build`, then everything is great. :beers:

**Comment by think2011** [comment]
1. Collect all error items with `var focusElements = {};` use error index to make a object key.
2. Because some function returns a promise，when promise done `Math.min` will find the smallest element as index, and focus it.

`grunt build ` complete👌

**Comment by huei90** [comment]
Cool! Nice Fix. :beers:

**Pull request merged**
