### PR TITLE
In case where there is more than one validator on an element, the recursive validation logic fails to wait until all validators have executed.

### PR DESCRIPTION
**Pull request by imranamans**

### CODE REVIEW

**Comment by huei90** [comment]
@imranamans please help me on using grunt build. Thanks!

**Comment by imranamans** [comment]
Hi Huei,

What help do you need on Grunt, I am not really familiar with Grunt, but let me know, I can try and help you with it.

**Comment by huei90** [comment]
https://github.com/huei90/angular-validation/blob/master/CONTRIBUTING.md

use `grunt build` to generate the `angular-validation.js` and `angular-validation.min.js` file

**Comment by imranamans** [comment]
Hi Huei,

Followed the steps and have built with grunt. Let me know if this helps.

**Comment by huei90** [comment]
Thanks @imranamans This is fine :beers:

**Pull request merged**
