### PR TITLE
Add a MessageId atrribute for customizing valid/invalid message position

### PR DESCRIPTION
**Pull request by lvarayut**
Since I have opened the issue, #69, I modified the code a little bit by adding a `message-id` attribute that is used to define an id name of a message element. Then, you could create the message element, which has the exact same id name. The message will be put in that element, so, you can arbitrary specify where you want to place the valid/invalid message. For example,

```html
        <form name="Form" id="form1">
                <label>Required</label>
                <input type="text"
                       name="requireWatch"
                       ng-model="form.required"
                       validator="required"
                       required-error-message="Required"
                       required-success-message="Good Required" autofocus="autofocus",
                       message-id="requireWatch"/> <!-- Specify an id name -->
                <span id="requireWatch"></span> <!-- Can be put wherever you want -->
        </form>
```

### CODE REVIEW

**Comment by toomu** [comment]
Any progress on this one, please?

**Comment by huei90** [comment]
@lvarayut

**Comment by lvarayut** [comment]
@toomu  I'm still very busy. So, I didn't make any progress on this feature yet. If you really want this feature, you can use my folk version [angular-validation](https://github.com/lvarayut/angular-validation),  `bower install lvarayut/angular-validation#master --save`

**NOTE:**   It provides your a flexible `message-id` attribute which allows you to place a success/error message wherever you want. However, you must define the `message-id` attribute on all the inputs.

**Comment by huei90** [comment]
As I mentioned

we need a default <span></span> if message-id is not given.

The idea is useful! Waiting for your contribution.
:beers:

**Comment by lvarayut** [comment]
@huei90 As a lot of people asking, I will do it in a fews day, might be this weekend.

**Comment by huei90** [comment]
Ok! See you soon =)

**Comment by lvarayut** [comment]
@huei90,  I have modified the directive code in order to support a default message and also made the `message-id` attribute work without `JQuery` dependency.  Moreover, I also fixed some errors in the unit tests and added some unit tests for the `message-id`. Finally, I fixed `Regular Expression` to only apply the test if the value is neither `undefined` or `null`.

Hopefully, it's useful for you.

**Comment by huei90** [comment]
@lvarayut many thanks for your help. Glad to see your commit here.

:beers: Thanks!

**Comment by huei90** [comment]
@lvarayut One more thing I think we can do more.

I think we should add a description of how to use MessageId on API.md

**Comment by lvarayut** [comment]
@huei90  Alright, I will update it soon :beers:

**Comment by huei90** [comment]
Thanks again @lvarayut

**Comment by Jeevanandanj** [comment]
Can we use folk version https://github.com/huei90/angular-validation? or can we go with the existing one https://github.com/huei90/angular-validation?

**Comment by huei90** [comment]
@Jeevanandanj what do you mean?

**Pull request merged**
