### PR TITLE
Added Demo of How to use Radio Button validation.

### PR DESCRIPTION
**Pull request by obender**
Added to Demo of How to use Radio Button validation.

### CODE REVIEW

**Comment by huei90** [comment]
Hi Thanks @obender 
I would like to merge the commit.

But it also refactor all the html structure.

Would you mind add only the part you modify? And why there is a file `q`?

**Comment by huei90** [comment]
Nudge @obender

**Comment by obender** [comment]
No need i a q file ....
Sorry for that, 

I had reformatted the html using Web storm formater... do you want me to undo it ?
I just added this code:
<div>
                    <label>Type:</label>
                    <input type="radio" name="active" ng-model="form.active" value="yes" validator="required"
                           message-id="invalidActive"/>Active
                    <input type="radio" name="active" ng-model="form.active" value="no" validator="required"
                           message-id="invalidActive"/>Not Active
                    <div id="invalidActive"></div>
                </div>

**Comment by huei90** [comment]
Yes, please add your code but don't modify others.

**Comment by huei90** [comment]
I have added the example in demo.
https://github.com/huei90/angular-validation/commit/440da134743cb617349b0588d9da2c567efe2734

Thanks @obender

**Pull request closed without merging**
