### PR TITLE
Adding message to invalid and valid callback functions.

### PR DESCRIPTION
**Pull request by tylergraf**
### Feature
I love all of the features you have here, I just wanted to be able to use my own error/success function to display the message so I added the message in the callback function.

#### How to use
**html**
``` html
<input type="text" ng-model="name" name="inputName" validator="required" valid-callback="validationValidHandler(message)" invalid-callback="validationInvalidHandler(message)">
```
**Javascript**
``` javascript
scope.validationValidHandler = function(message){
  // you now have access to the error message
  displayMessage(message, 'success');
};

scope.validationInvalidHandler = function(message){
  // you now have access to the error message
  displayMessage(message, 'error');
};
```

### Bug Fix
I changed `inValidCallback` to `invalidCallback` since the html attribute in the docs is `invalid-callback` not `in-valid-callback` :smile: 

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by huei90** [comment]
Cool, it's useful. Before merging, do you mind giving a documentation on **README.md** **API.md** about this change?

**Comment by huei90** [comment]
and `in-valid-callback` is the bug I think XD

**Comment by tylergraf** [comment]
Cool. Yeah, I'll add documentation. Thanks!

**Comment by huei90** [comment]
Thanks!

**Comment by tylergraf** [comment]
@huei90 Sorry I haven't gotten around to this until now. I think it's ready to go now.

**Comment by huei90** [comment]
:+1: @tylergraf Thanks for this fixing. Great :beers:

**Pull request merged**
