### PR TITLE
ES6 import/require Support

### PR DESCRIPTION
**Pull request by brunowego**
Simple solution for who uses es6 syntax.

### CODE REVIEW

**Comment by huei90** [comment]
What about using the current file `main.js`?

**Comment by brunowego** [comment]
@huei90 my mistake, I have not seen. I will close this 👍

**Comment by huei90** [comment]
Don't worry 💪

**Comment by nathan6137** [comment]
@brunowego @hueitan So how can i use ES6 import/require? I am getting an error.

**Pull request closed without merging**
