### PR TITLE
Updated validate directive to compile the error and success html strings (useful for translation keys)

### PR DESCRIPTION
**Pull request by jamhall**
Added compile service to compile the error and success strings.

For example, you may wish to use translation keys for the error and success messages:

```
  app.config(['$validationProvider', '$parseProvider', function ($validationProvider) {
    var expression = {
      required: function (value) {
        return !!value;
      }
    };

    var defaultMsg = {
      required: {
        error: 'generic.form.validations.required.error',
        success: 'generic.form.validations.required.success'
      }
    };

    $validationProvider.setExpression(expression).setDefaultMsg(defaultMsg);

    $validationProvider.setErrorHTML(function (msg) {
      var html = "<span class=\"label label-danger\">{{ '{0}' | translate }}</span>".replace('{0}', msg);
      return html;
    });

    $validationProvider.setSuccessHTML(function (msg) {
      var html = "<span class=\"label label-success\">{{ '{0}' | translate }}</span>".replace('{0}', msg);
      return html;
    });
}]);
```

Please note, I have built it using the `grunt build` task but I have not commited the build files.

Cheers,

Jamie

### CODE REVIEW

**Comment by jamhall** [comment]
Reference: https://github.com/huei90/angular-validation/issues/96

**Comment by huei90** [comment]
Hi @jamhall Thanks for this.

Would you mind do grunt build on this?

**Comment by jamhall** [comment]
Added :-)

**Comment by huei90** [comment]
Close it. Open if needed.

**Comment by huei90** [comment]
Ok, you are right. I'm thinking about this fix now, it make more sense to us using angular compile.

**Comment by huei90** [comment]
New PR here.
https://github.com/huei90/angular-validation/pull/184

**Pull request closed without merging**
