### PR TITLE
Toggle has-error on bootstrap form-group

### LINKED ISSUE #80: Toggle has-error on parent form-group
In Bootstrap you can make label, input and error message all have red text/outline if you set `.has-error` on parent container, typically `.form-group`

I was able to add in source code with:

    formGroupElem = element.parents('.form-group:first')
    formGroupElem.addClass('has-error');
    formGroupElem.removeClass('has-error');

I am doing it atm inside `invalidFunc` and `validFunc`.

Would you accept PR with it? Or would you suggest some other approach to address it? Maybe some callback that would be possible to set like `$validationProvider.setErrorHTML`?

### PR DESCRIPTION
**Pull request by tb**
toggle has-error on parent form-group with $validationProvider valid/invalid callbacks
resolves #80

### CODE REVIEW

**Comment by huei90** [comment]
Thanks @tb 

This is for bootstrap solution only.

Perhaps other way to provide global solution for it?

**Comment by tb** [comment]
@huei90 thats what I did, see https://github.com/tb/angular-validation/tree/bootstrap-form-group#integrating-with-twitter-bootstrap

**Comment by huei90** [comment]
Nice @tb I have looked your code. :+1: 

But I need some more

1. grunt build
2. global validCallback should be initial to `null` also giving some `parameter`

**Comment by lucax88x** [comment]
+ this is a necessary feature

**Comment by huei90** [comment]
calling @tb

**Comment by tb** [comment]
@huei90 I have updated PR

**Comment by huei90** [comment]
Cool. Roger that :beers:

**Pull request merged**
