### PR TITLE
Add some description of the Message-id attribute

### PR DESCRIPTION
**Pull request by lvarayut**
Refer to #70, sorry for late PR. I just added some description of the `message-id` attribute to the `API.md`.

### CODE REVIEW

**Comment by huei90** [comment]
@lvarayut It's conflict here. Would you mind update to the latest one and PR again?

Thanks again !!

**Comment by lvarayut** [comment]
@huei90 I presently don't want to update my fork due to it's used in two of my projects. You might try to merge it with your current `API.md`. In case that it doesn't work. You can simply copy my paragraphs, put it into yours, and ignore this PR.

**Comment by huei90** [comment]
OK thanks @lvarayut

**Comment by huei90** [comment]
DONE!

**Comment by lvarayut** [comment]
:beers:

**Pull request closed without merging**
