### PR TITLE
Fixed no-validation-message condition

### PR DESCRIPTION
**Pull request by rmngrc**
This simple check makes the no-validation-message work. Otherwise, even with no-validation-message="true" always was executing checkValidation and stopping the form of being submitted.

### CODE REVIEW

**Comment by huei90** [comment]
Hi @rmngrc We do have the directive to handle this.
https://github.com/huei90/angular-validation/blob/master/src/directive.js#L345

**Comment by rmngrc** [comment]
Hi @huei90, the directive was never working, that is why I came up with this solution.

Anyway, it checks the pressence of the directive and its value so is basically the same.

**Comment by huei90** [comment]
Thanks @rmngrc for reporting this.
I have checked that seems 1.3 observer has breaking change, we should handle the $observe use

**Comment by huei90** [comment]
Fix.

**Comment by huei90** [comment]
@rmngrc you are right.

see the fix commit.

https://github.com/huei90/angular-validation/commit/0946ed4ab22611aaf68b625ac9028a9767f012f7

**Pull request closed without merging**
