### PR TITLE
demo page style update

### PR DESCRIPTION
**Pull request by Nazanin1369**
Improved demo page styling and design.

### CODE REVIEW

**Comment by Nazanin1369** [comment]
@huei90 Could u plz review this change.

**Comment by lvarayut** [comment]
It looks good to me. Just one small thing, do you prefer to align your code using 2 or 4 spaces? In the JavaScript code, everything seems to be aligned using 2 spaces.

**Comment by Nazanin1369** [comment]
Sure.

On Saturday, May 21, 2016, Varayut Lerdkanlayanawat <
notifications@github.com> wrote:

> It looks good to me. Just one small thing, do you prefer to align your
> code using 2 or 4 spaces? In the JavaScript code, everything seems to be
> aligned using 2 spaces.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/huei90/angular-validation/pull/208#issuecomment-220773081>
>


-- 
Best Regards,

**Comment by huei90** [comment]
Hello, feel free to merge or change, you have the authority to do it =)

**Comment by Nazanin1369** [comment]
Thank you @huei90

**Pull request merged**
