### PR TITLE
Reset callback

### PR DESCRIPTION
**Pull request by lucax88x**
Added a reset callback with documentation with also some gernal documentation on general callbacks which weren't present in the API documentation

### CODE REVIEW

**Comment by huei90** [comment]
In what case people need resetCallback?

We can do it by `ng-click="reset(Form)"`

```
$scope.reset = function (form) {
    $validationProvider.reset(form);
    // callback here
}
```

**Comment by huei90** [comment]
Also this resetCallback will works in every input.

**Comment by lucax88x** [comment]
it's used to perform graphical variations on html elements when a reset is performed.

Are you sure about your last statement?

**Comment by huei90** [comment]
https://github.com/lucax88x/angular-validation/blob/blessed/src/validator.directive.js#L229

This works on every on - reset event.

```html
<form name="Form1">
 <input ... />
 <input ... />
 <input ... />
 <button ng-click="reset(Form1)"></button>
</form>
```

then resetCallback will execute 3 times.

**Comment by lucax88x** [comment]
yeah, this is correct, as you can see, the callbacks need a element parameter.

for example:

```javascript
this.$validation.validCallback = function(element) {
                $(element).removeClass('has-error').addClass('has-success-tick');
            };
            this.$validation.invalidCallback = function(element) {
                $(element).removeClass('has-success-tick').addClass('has-error');
            };
            this.$validation.resetCallback = function(element) {
                $(element).removeClass('has-error').removeClass('has-success-tick');
            };
```

**Comment by huei90** [comment]
Oh I got your point.

resetCallback has the same purpose as validCallback, invalidCallback

**Comment by lucax88x** [comment]
yes, but used when a reset is performed

**Comment by huei90** [comment]
Thanks @lucax88x This looks reasonable. :beers: 

@Nazanin1369 @lucax88x 

We now have a lot of callback within every section.

maybe it's time we need to define the callback SPEC.

**Comment by Nazanin1369** [comment]
Agree.

**Comment by huei90** [comment]
@lucax88x I'm going to merge this feature. Do you want to create a test case for this or I can do it.

**Comment by lucax88x** [comment]
what if you create a spec for valid callback & invalid callback and I add one for reset?

**Comment by huei90** [comment]
Ok thanks @lucax88x I will create another Issue for the spec.

and I merge the reset feature now.

**Pull request merged**
