### PR TITLE
Allow passing of a parameter to validation rule and added min and max length rules

### PR DESCRIPTION
**Pull request by lopsided**
As per title. This allows you to set rules like:

```
<input validator="required, minlength=6">
````

The `6` is extracted and passed as a parameter to the validator. I have added `minlength` and `maxlength` to the default rules but this will work for any custom expression too.

If you want to merge this let me know and I'll update the docs.

Cheers

### CODE REVIEW

**Comment by huei90** [comment]
Cool! It's looks nice. Waiting for you doc :beers:

**Comment by eremsoft** [comment]
It works for me.

In html:
&lt;input ng-model="form.name" class="text-box single-line textMedium" name="Name" minimumlength="5" validator="required, maxlength" valid-method="blur" /&gt;

In rules:
var expression = {
                   maxlength: function(value, scope, element, attrs){
                        return value.length <= parseInt(attrs.minimumlength);
                    }
                };
var defaultMsg = {
                    maxlength:{
                        error: function(attrs){
                        return 'The field must be a string with a maximum length of '+ attrs.minimumlength;
                        },
                        success: ''
                    }
                };

in angular-validation.js change invalidFunc:
var invalidFunc = function(element, validMessage, validation, scope, ctrl, attrs) {
                    var messageElem,
                        messageToShow = validMessage || $validationProvider.getDefaultMsg(validation).error;
                    if (messageToShow.constructor === Function) {
                        messageToShow = messageToShow.call(this, attrs)                        
                    }

and change its call:
error: function() {
                                return invalidFunc(element, attrs[errorMessage], validator, scope, ctrl, attrs);
                            }

**Comment by lopsided** [comment]
@huei90 docs added

**Comment by huei90** [comment]
Cool!!! Many Thanks.

**Pull request merged**
